# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubToTerraform < Formula
  desc "Get current GitHub configuration and create Terraform code for it"
  homepage "https://github.com/shmileee/github-to-terraform"
  version "0.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shmileee/github-to-terraform/releases/download/v0.0.1/github-to-terraform_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "2e9ea8d197d3cd4a944ed226fcb5fa9e6a0f0bb8602ba1cef5468c9753fe4d60"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shmileee/github-to-terraform/releases/download/v0.0.1/github-to-terraform_0.0.1_Linux_x86_64.tar.gz"
      sha256 "91322d053cb3afadeb293029bae3f14e796f5345b2fd5b3990e44376cac87d0a"
    end
  end

  def install
    bin.install "github-to-terraform"
  end
end
